# Generated by Django 5.2.17 on 2026-08-24 19:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carregador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identificador_fisico', models.CharField(max_length=40)),
                ('metodo_identificacao', models.CharField(choices=[('token', 'Token'), ('qrcode', 'QR Code')], max_length=10)),
                ('apelido', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('adicionado', 'Aguardando liberação'), ('liberado', 'Liberado'), ('carregando', 'Carregando'), ('aguardando_pagamento', 'Pagamento pendente'), ('concluido', 'Concluído')], default='adicionado', max_length=25)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('inicio_carregamento', models.DateTimeField(blank=True, null=True)),
                ('momento_bateria_cheia', models.DateTimeField(blank=True, null=True)),
                ('resumo_final', models.JSONField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('pix', 'Pix'), ('credito', 'Cartão de crédito'), ('debito', 'Cartão de débito')], max_length=10, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carregadores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
