# Generated by Django 5.2.17 on 2026-08-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_carregador_concluido_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregador',
            name='endereco',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='carregador',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carregador',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
