# Generated by Django 5.2.17 on 2026-08-25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("painel", "0004_distribuidora_carregador_distribuidora"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PontoCarregamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=80)),
                (
                    "identificador_fisico",
                    models.CharField(
                        help_text="Token ou conteúdo do QR Code impresso no carregador.",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("endereco", models.CharField(max_length=200)),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ]
                    ),
                ),
                (
                    "preco_kwh",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Valor em reais cobrado do motorista por kWh consumido.",
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                        verbose_name="Preço por kWh",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "distribuidora",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pontos_carregamento",
                        to="painel.distribuidora",
                    ),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        limit_choices_to={"is_staff": True},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pontos_carregamento",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ponto de carregamento",
                "verbose_name_plural": "Pontos de carregamento",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="carregador",
            name="ponto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sessoes",
                to="painel.pontocarregamento",
            ),
        ),
        migrations.AddField(
            model_name="carregador",
            name="tarifa_kwh_aplicada",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preço por kWh congelado no início desta sessão.",
                max_digits=7,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="carregador",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("ponto__isnull", False),
                    models.Q(("status", "concluido"), _negated=True),
                ),
                fields=("ponto",),
                name="uma_sessao_ativa_por_ponto",
            ),
        ),
    ]
