# Generated by Django 5.2.17 on 2026-08-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carregador',
            name='concluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
