# Generated by Django 5.2.17 on 2026-08-25 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_carregador_endereco_carregador_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('regiao', models.CharField(blank=True, max_length=100)),
                ('tarifa_custo_kwh', models.DecimalField(decimal_places=4, help_text='R$/kWh que a WeCharge paga para essa distribuidora (custo de energia).', max_digits=6)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Distribuidora',
                'verbose_name_plural': 'Distribuidoras',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='carregador',
            name='distribuidora',
            field=models.ForeignKey(blank=True, help_text='Distribuidora de energia que abastece este ponto de recarga.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carregadores', to='painel.distribuidora'),
        ),
    ]
