# Generated by Django 5.2.17 on 2026-08-27 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0007_token_5_caracteres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontocarregamento',
            name='identificador_fisico',
            field=models.CharField(blank=True, help_text='Token de 5 caracteres, gerado automaticamente ao cadastrar o carregador e impresso no QR Code.', max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='O token deve ter exatamente 5 caracteres (letras e números).', regex='^[A-Z0-9]{5}$')]),
        ),
    ]
