"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega as variáveis do arquivo .env (na raiz do projeto, ao lado do
# manage.py) para dentro de os.environ, se o arquivo existir. Assim,
# GOOGLE_MAPS_API_KEY, OPENAI_API_KEY etc. podem ficar num arquivo local
# em vez de precisar configurar no sistema operacional.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ypa$ye095kuqwgjwi35$c&*svv9-$!pjc&fs+n#yaaipmmt0q^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://*.trycloudflare.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'paginas',      # site público (institucional)
    'contas',       # login / logout
    'painel',       # área do usuário comum (motorista)
    'operador',     # área do administrador (operador do eletroposto)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = []  # pastas extras de static globais (se precisar futuramente)

# Autenticação: para onde mandar o usuário em cada situação
LOGIN_URL = 'contas:login'
LOGIN_REDIRECT_URL = 'contas:pos_login'   # decide painel de usuário ou de operador
LOGOUT_REDIRECT_URL = 'paginas:home'

# Permite logar tanto com o username quanto com o e-mail cadastrado — a
# tela de login já mostrava "Usuário ou e-mail", mas sem isso só o
# username funcionava de verdade. Mantém o ModelBackend padrão em
# seguida como reserva (ex.: para o /admin, que não usa nosso formulário).
AUTHENTICATION_BACKENDS = [
    'contas.backends.UsuarioOuEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# IoI Chat — assistente de IA da área do usuário (mapa de carregadores
# próximos). Sem essa variável configurada, o botão do chat mostra um
# aviso em vez de tentar chamar a API sem chave.
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-5-mini')

# Mapa (Leaflet): o Django, por padrão, usa Referrer-Policy "same-origin",
# o que faz o navegador não enviar o Referer aos servidores de tiles e o
# OpenStreetMap responder 403 ("Access blocked"). Esta política envia só a
# origem do site (ex.: http://127.0.0.1:8000) em requisições externas.
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
